### PR TITLE
Avoid needlessly deleting WeakMap entries

### PR DESCRIPTION
**Pull request by novemberborn**
Per https://github.com/dojo/shim/issues/6.

### CODE REVIEW

**Comment by novemberborn** [comment]
Interesting. CI fails because `state` is destroyed when the action is destroyed, but the `do` function is only removed after garbage collection. This causes an error at https://github.com/dojo/actions/blob/9e1ce4323651f3f1c99946a8e72484e6575cfad7/src/createAction.ts#L119.

In other words deleting the `do` and `configure` function from the WeakMap signals that the action has been destroyed. That seems like a side-effect so maybe we need to explicitly track destruction and guard against that?

**Comment by kitsonk** [comment]
> That seems like a side-effect so maybe we need to explicitly track destruction and guard against that?

That seems counter productive.  Isn't it true that in this case, deleting from the `WeakMap` isn't unnecessary?  Adding another "map" or whatever of destroyed actions seems non-sensical.

**Comment by novemberborn** [comment]
> Isn't it true that in this case, deleting from the WeakMap isn't unnecessary? Adding another "map" or whatever of destroyed actions seems non-sensical.

It feels like an exception to the pattern though, where we use the WeakMap to store a private value and don't need to care about cleaning it up. Here we need to clean it up because other code uses the presence in the WeakMap as a guard. I think we should use an explicit guard, though if that ends up being inside another WeakMap then yea that is a bit weird…

**Comment by kitsonk** [comment]
> It feels like an exception to the pattern though, where we use the WeakMap to store a private value and don't need to care about cleaning it up. Here we need to clean it up because other code uses the presence in the WeakMap as a guard.

Then we could/should use a `Map` then, since there is a hard relationship, not a weak one?

**Comment by novemberborn** [comment]
> Then we could/should use a Map then, since there is a hard relationship, not a weak one?

Ah yes will do that.

**Comment by novemberborn** [comment]
On second thought… we need the WeakMap so that the action can be garbage collected without explicit destruction. Like with https://github.com/dojo/compose/pull/48 we have cases where destruction can be observed. That'll have to be part of the pattern.

**Pull request closed without merging**
